### ISSUE TITLE
tensorized_lookahead_language_model SyntaxError

### ISSUE THREAD

**Issue by DTDwind** [freewym/espresso#10]
Hi~  I was running the asr_wsj and got SyntaxError: invalid syntax.

this is the info.
```
File "/share/nas165/QAQ/espresso/fairseq/models/tensorized_lookahead_language_model.py", line 61
    self.lm_decoder: FairseqIncrementalDecoder = word_lm.decoder
                   ^
SyntaxError: invalid syntax

```
Anyone could help me?
tyvm

**Comment by freewym** [comment]
Oh, I guess you are using Python3.5. A higher version would probably work for this case.

**Comment by DTDwind** [comment]
I try to use python 3.6, but it still not works. When it was running, it would stop at "PENDING JOBS" like this:
```
############################################################################
 - PENDING JOBS - PENDING JOBS - PENDING JOBS - PENDING JOBS - PENDING JOBS
############################################################################
 933910 0.50000 make_fbank QAQ     Eqw   10/20/2019 16:56:40     1 4
``` 
I trace my log and get this:
```
ERROR (compute-fbank-feats[5.5.427~1-abfb9]:Read4ByteTag():wave-reader.cc:56) WaveData: expected 4-byte chunk-name, got read error
```
Could you give me some suggestions？

**Comment by freewym** [comment]
What does the log say about the command it is executing? Mine is like:
`paste-feats --length-tolerance=2 "ark:compute-fbank-feats  --verbose=2 --config=conf/fbank.conf scp,p:exp/make_fbank/train_si284/wav.1.scp ark:- |" "ark,s,cs:compute-kaldi-pitch-feats --verbose=2 --config=conf/pitch.conf scp,p:exp/make_fbank/train_si284/wav.1.scp ark:- | process-kaldi-pitch-feats  ark:- ark:- |" ark:- | copy-feats --compress=true --write-num-frames=ark,t:exp/make_fbank/train_si284/utt2num_frames.1 ark:- ark,scp:/home/ywang/fairseq/examples/asr_wsj/fbank/raw_fbank_pitch_train_si284.1.ark,/home/ywang/espresso/examples/asr_wsj/fbank/raw_fbank_pitch_train_si284.1.scp
`
Maybe you can track the entries in wav.scp to see if they are pointing to the correct files.

**Comment by DTDwind** [comment]
Hi~ I edit the wav.scp and success, but my python version go back to 3.5 now.
this is my path.sh
```
MAIN_ROOT=$PWD/../..
KALDI_ROOT=$MAIN_ROOT/speech_tools/kaldi

# BEGIN from kaldi path.sh
[ -f $KALDI_ROOT/tools/env.sh ] && . $KALDI_ROOT/tools/env.sh
export PATH=$PWD/utils/:$KALDI_ROOT/tools/openfst/bin:$KALDI_ROOT/tools/sctk/bin:$PWD:$PATH
[ ! -f $KALDI_ROOT/tools/config/common_path.sh ] && echo >&2 "The standard file $KALDI_ROOT/tools/config/common_path.sh is not present -> Exit!" && exit 1
. $KALDI_ROOT/tools/config/common_path.sh
export LC_ALL=C
# END
export PATH=/usr/bin/python3.6:$PATH
#export PATH=~/anaconda3/bin:$PATH
export PATH=$MAIN_ROOT:$MAIN_ROOT/speech_tools:$PATH
#PYTHONPATH=/usr/bin/python3.6
export PYTHONPATH=$MAIN_ROOT:$MAIN_ROOT/speech_tools:$PYTHONPATH
export PYTHONUNBUFFERED=1
```
I  don't know why it still get 3.5.
Could you give me some suggestions？
tyvm

**Comment by DTDwind** [comment]
/usr/bin/python3.6 is executable.

**Comment by freewym** [comment]
What is /usr/bin/python3 pointing at? It should pointing to python3.6, and then set `PATH=/usr/bin:$PATH`

**Comment by DTDwind** [comment]
My /usr/bin/python3 is /usr/bin/python3, but I am not root, I can't change what it is pointing at...

**Comment by freewym** [comment]
Maybe your python3 is actually Python3.5 you could check it by running /usr/bin/python3 and looking at its shown version info.

In order to use python3.6 in your case, after  setting `PATH=/usr/bin:$PATH`, replace all appearance of "python3" to "python3.6" in `run.sh`

**Comment by DTDwind** [comment]
OK, I make a directory, and make a link ```python3 -> /usr/bin/python3.6``` .
Then I set the path.sh to the directory, which is created by me.
It works!
Thank you very much. <3
