### ISSUE TITLE
Error in fp16 training

### ISSUE THREAD

**Issue by Shujian2015** [freewym/espresso#13]
Hi @freewym , have you had a chance to train the model with float 16 precision? I experienced such error in the swb recipe:

`-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "<path>/codebase/espresso/env/lib64/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "<path>/codebase/espresso/speech_train.py", line 354, in distributed_main
    main(args, init_distributed=True)
  File "<path>/codebase/espresso/speech_train.py", line 128, in main
    train(args, trainer, task, epoch_itr)
  File "<path>/codebase/espresso/speech_train.py", line 173, in train
    log_output = trainer.train_step(samples)
  File "<path>/codebase/espresso/fairseq/trainer.py", line 342, in train_step
    raise e
  File "<path>/codebase/espresso/fairseq/trainer.py", line 306, in train_step
    ignore_grad
  File "<path>/codebase/espresso/fairseq/tasks/fairseq_task.py", line 249, in train_step
    optimizer.backward(loss)
  File "<path>/codebase/espresso/fairseq/optim/fp16_optimizer.py", line 103, in backward
    loss.backward()
  File "<path>/codebase/espresso/env/lib64/python3.6/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "<path>/codebase/espresso/env/lib64/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: expected scalar type Float but found Half`

**Comment by Shujian2015** [comment]
And do you think it is a good idea if I switch to `apex.amp` from `.half()`?

**Comment by freewym** [comment]
I have not tried fp16 as I don't have access to V100. Are you able to train with other fairseq tasks?

I am not familiar with apex.amp either

**Comment by freewym** [comment]
Not sure if [this line](https://github.com/freewym/espresso/blob/master/fairseq/criterions/label_smoothed_cross_entropy_with_wer.py#L63) would cause your problem, where that tensor should not been used unless you are using unigram smoothing. You can do some hack to make this tensor of half type to see.

**Comment by Shujian2015** [comment]
Thanks @freewym , for your LM model in swbd, fp16 is 3-4 times faster. 
Let me try to play with that part tomorrow.

**Comment by freewym** [comment]
...or maybe at [this line](https://github.com/freewym/espresso/blob/master/fairseq/data/scp_dataset.py#L167). convert to float16 instead of float32 if fp16 is true

**Comment by Shujian2015** [comment]
:p actually there are some tensors that are supposed to change from half to float. still searching for them.

**Comment by Shujian2015** [comment]
Hi @freewym , that doesn't help. Do you think there is anything to do with batchnorm2d? Saw an example doing normalization this way: https://github.com/pytorch/fairseq/blob/master/fairseq/models/wav2vec.py#L233

**Comment by freewym** [comment]
You can simply remove batchnorm2d to see.

**Comment by Shujian2015** [comment]
so..... problem is gone when I turn of attention......

**Comment by freewym** [comment]
Could you please find out which tensor in the forward() of attention is not not of dtype fp16?

**Comment by Shujian2015** [comment]
Hi @freewym , do you have any suggestions on how to debug this efficiently? I am new to PyTorch and I am trying to convert any suspicious tensor. It is quite inefficient. Thanks in advance.

**Comment by freewym** [comment]
You said there is no problem with the attention module off, so I suspect that some tensor in forward() of the attention is not converted to fp16. Since there are only a few tensors there, I am thinking of checking dtype of each of these tensors.

**Comment by Shujian2015** [comment]
Thanks. Let me check that over the weekend. The model without attention seems unable to learn the data. WER and CER don't decease in the first few epochs.

**Comment by Shujian2015** [comment]
Solved by replace [this line](https://github.com/freewym/espresso/blob/master/fairseq/modules/speech_attention.py#L78):
`        attn_scores = utils.softmax(attn_scores, dim=0,
            onnx_trace=self.onnx_trace).type_as(attn_scores)  # len x bsz`

with [this line](https://github.com/pytorch/fairseq/blob/master/fairseq/models/lstm.py#L299):
`attn_scores = F.softmax(attn_scores, dim=0)  # srclen x bsz`

**Comment by Shujian2015** [comment]
A quick update about this topic: LM is 3-4 times faster in training without much degrade in ppl. However for seq2seq, the speedup is only 30% and wer on dev is 2% off. Probably not worth it on seq2seq part.
