### ISSUE TITLE
Verify WER by scoring with Kaldi 

### ISSUE THREAD

**Issue by ahmedalbahnasawy** [freewym/espresso#17]
Hi authors,
I'm using **Librispeech run.sh** recipe. I trained the acoustic model (speech_conv_lstm_librispeech) using 4 GPU 1080ti But I'm facing this error while doing kaldi scoring.
local/score.sh data/test_clean exp/lstm/decode_test_clean_shallow_fusion
run.pl: job failed, log is in exp/lstm/decode_test_clean_shallow_fusion/scoring_kaldi/log/score.log
My second question
Is there any documentation for using my pre-trained model to decode audio wav, i would like to compare the decoding speed between ESPNet and Esspresso [https://arxiv.org/abs/1909.08723](url)

**Comment by freewym** [comment]
Can you please open the log file to see what the error message is?

You need to first prepare a data folder containing wav.scp, utt2spk files (look at [here](http://kaldi-asr.org/doc/kaldi_for_dummies.html#kaldi_for_dummies_acoustic) for explanations), and then follow the steps of extracting  filterbank feature in the Librispeech recipe (those in stage 2).

**Comment by ahmedalbahnasawy** [comment]
the idea that i opened the file "exp/lstm/decode_test_clean_shallow_fusion/scoring_kaldi/log/score.log"  
:q!
# cat exp/lstm/decode_test_clean_shallow_fusion/scoring_kaldi/hyp_filt.txt | compute-wer --text --mode=present ark:exp/lstm/decode_test_clean_shallow_fusion/scoring_kaldi/test_filt.txt ark,p:- >& exp/lstm/decode_test_clean_shallow_fusion/scoring_kaldi/wer 
that means there is no error in score.log

**Comment by freewym** [comment]
Can you run directly in the command line with the command from the log you just show? You may have to first do `. path.sh` before running that command

**Comment by ahmedalbahnasawy** [comment]
Hi thank you for your response. 
till now i didn't get the kaldi score using score.sh function **BUT**
I wrote this simple script to decode any audio wav. I can write recipe to load the trained model once   
`if [ ! -f path.sh ] || [ ! -f cmd.sh ]; then
    echo "Please change current directory to recipe directory e.g., examples/asr_librispeech/path.sh”
    exit 1
fi

. ./path.sh

export PYTHONPATH=$PYTHONPATH:/espresso/
# feature configuration
do_delta=false
affix=
lm_affix=
lmdir=exp/lm_lstm${lm_affix:+_${lm_affix}}
echo {$lmdir}
free_gpu=3
dir=exp/lstm${affix:+_$affix}
checkpoint=checkpoint_best.pt
lm_checkpoint=checkpoint_best.pt
kaldi_scoring=true
# decoding parameter
decode_config=
decode_dir=decode
stage=0
stop_stage=100
# download related
cmvn=/espresso/examples/asr_librispeech/data/train_960/cmvn.ark
. utils/parse_options.sh || exit 1;

train_cmd=
decode_cmd=

wav=$1
download_dir=${decode_dir}/download

if [ $# -lt 1 ]; then
    echo "${help_message}"
    exit 1;
fi

set -e
set -u
set -o pipefail


dir=${download_dir}/${models}
mkdir -p ${dir}

# Check file existence
base=$(basename $wav .wav)
decode_dir=${decode_dir}/${base}

if [ ${stage} -le 0 ] && [ ${stop_stage} -ge 0 ]; then
    echo "stage 0: Data preparation"

    mkdir -p ${decode_dir}/data
    echo "$base $wav" > ${decode_dir}/data/wav.scp
    echo "X $base" > ${decode_dir}/data/spk2utt
    echo "$base X" > ${decode_dir}/data/utt2spk
    echo "$base X" > ${decode_dir}/data/text
fi

if [ ${stage} -le 1 ] && [ ${stop_stage} -ge 1 ]; then
    echo "stage 1: Feature Generation"

   steps/make_fbank_pitch.sh --cmd "$train_cmd" --nj 1 --write_utt2num_frames true \
        ${decode_dir}/data ${decode_dir}/log ${decode_dir}/fbank

    feat_recog_dir=${decode_dir}/dump; mkdir -p ${feat_recog_dir}
    dump.sh --cmd "$train_cmd" --nj 1 --do_delta ${do_delta} \
        ${decode_dir}/data/feats.scp ${cmvn} ${decode_dir}/log \
        ${feat_recog_dir}
fi
dict=/espresso/examples/asr_librispeech/data/lang/train_960_unigram5000_units.txt
if [ ${stage} -le 1 ]; then
  echo "Stage 1: Decoding"
  opts=""
  path=$dir/$checkpoint
  decode_affix=
  lm_shallow_fusion=true
  if $lm_shallow_fusion; then
    path="$path:$lmdir/$lm_checkpoint"
    opts="$opts --lm-weight 0.47 --eos-factor 1.5"
    decode_affix=shallow_fusion
  fi
    path=/espresso/examples/asr_librispeech/exp/lstm/${checkpoint}:/espresso/examples/asr_librispeech/exp/lm_lstm/${lm_checkpoint}
    feat=${feat_recog_dir}
    text=${decode_dir}/token_text
    CUDA_VISIBLE_DEVICES=$(echo $free_gpu | sed 's/,/ /g' | awk '{print $1}') speech_recognize.py \
      --task speech_recognition --user-dir /espresso --max-tokens 15000 --max-sentences 24 \
      --num-shards 1 --shard-id 0 --test-feat-files $feat/feats.scp --test-text-files $text \
      --dict $dict --remove-bpe sentencepiece \
      --max-source-positions 9999 --max-target-positions 999 \
      --path $path --beam 60 --max-len-a 0.08 --max-len-b 0 --lenpen 1.0 \
      --results-path $dir/decode_eval${decode_affix:+_${decode_affix}} $opts \
      2>&1 | tee $dir/logs/decode_eval${decode_affix:+_${decode_affix}}.log
    if $kaldi_scoring; then
      echo "here111"
      echo "verify WER by scoring with Kaldi..."
      local/score.sh data/$dataset $dir/decode_$dataset${decode_affix:+_${decode_affix}}
      cat $dir/decode_$dataset${decode_affix:+_${decode_affix}}/scoring_kaldi/wer
    fi
fi
`

**Comment by ahmedalbahnasawy** [comment]
Hi thank you for your response, 
its not path issue and till now i didnt get the score from score.sh function
I wrote script that decode any audio wave and it could help anyone. I'm writing also another recipe which load the trained lm and acoustic model once. 
`if [ ! -f path.sh ] || [ ! -f cmd.sh ]; then
    echo "Please change current directory to recipe directory e.g., examples/asr_librispeech/path.sh”
    exit 1
fi
. ./path.sh
export PYTHONPATH=$PYTHONPATH:/espresso/
do_delta=false
affix=
lm_affix=
lmdir=exp/lm_lstm${lm_affix:+_${lm_affix}}
echo {$lmdir}
free_gpu=3
dir=exp/lstm${affix:+_$affix}
checkpoint=checkpoint_best.pt
lm_checkpoint=checkpoint_best.pt
kaldi_scoring=true
decode_dir=decode
stage=0
stop_stage=100
cmvn=/espresso/examples/asr_librispeech/data/train_960/cmvn.ark
. utils/parse_options.sh || exit 1;

train_cmd=
decode_cmd=

wav=$1
download_dir=${decode_dir}/download

if [ $# -lt 1 ]; then
    echo "${help_message}"
    exit 1;
fi

set -e
set -u
set -o pipefail


dir=${download_dir}/${models}
mkdir -p ${dir}

base=$(basename $wav .wav)
decode_dir=${decode_dir}/${base}

if [ ${stage} -le 0 ] && [ ${stop_stage} -ge 0 ]; then
    echo "stage 0: Data preparation"

    mkdir -p ${decode_dir}/data
    echo "$base $wav" > ${decode_dir}/data/wav.scp
    echo "X $base" > ${decode_dir}/data/spk2utt
    echo "$base X" > ${decode_dir}/data/utt2spk
    echo "$base X" > ${decode_dir}/data/text
fi

if [ ${stage} -le 1 ] && [ ${stop_stage} -ge 1 ]; then
    echo "stage 1: Feature Generation"

   steps/make_fbank_pitch.sh --cmd "$train_cmd" --nj 1 --write_utt2num_frames true \
        ${decode_dir}/data ${decode_dir}/log ${decode_dir}/fbank

    feat_recog_dir=${decode_dir}/dump; mkdir -p ${feat_recog_dir}
    dump.sh --cmd "$train_cmd" --nj 1 --do_delta ${do_delta} \
        ${decode_dir}/data/feats.scp ${cmvn} ${decode_dir}/log \
        ${feat_recog_dir}
fi
dict=/espresso/examples/asr_librispeech/data/lang/train_960_unigram5000_units.txt
if [ ${stage} -le 1 ]; then
  echo "Stage 1: Decoding"
  opts=""
  path=$dir/$checkpoint
  decode_affix=
  lm_shallow_fusion=true
  if $lm_shallow_fusion; then
    path="$path:$lmdir/$lm_checkpoint"
    opts="$opts --lm-weight 0.47 --eos-factor 1.5"
    decode_affix=shallow_fusion
  fi
    path=/espresso/examples/asr_librispeech/exp/lstm/${checkpoint}:/espresso/examples/asr_librispeech/exp/lm_lstm/${lm_checkpoint}
    feat=${feat_recog_dir}
    text=${decode_dir}/token_text
    CUDA_VISIBLE_DEVICES=$(echo $free_gpu | sed 's/,/ /g' | awk '{print $1}') speech_recognize.py \
      --task speech_recognition --user-dir /espresso --max-tokens 15000 --max-sentences 24 \
      --num-shards 1 --shard-id 0 --test-feat-files $feat/feats.scp --test-text-files $text \
      --dict $dict --remove-bpe sentencepiece \
      --max-source-positions 9999 --max-target-positions 999 \
      --path $path --beam 60 --max-len-a 0.08 --max-len-b 0 --lenpen 1.0 \
      --results-path $dir/decode_eval${decode_affix:+_${decode_affix}} $opts \
      2>&1 | tee $dir/logs/decode_eval${decode_affix:+_${decode_affix}}.log
    if $kaldi_scoring; then
      echo "verify WER by scoring with Kaldi..."
      local/score.sh data/$dataset $dir/decode_$dataset${decode_affix:+_${decode_affix}}
      cat $dir/decode_$dataset${decode_affix:+_${decode_affix}}/scoring_kaldi/wer
    fi
fi
`

**Comment by ahmedalbahnasawy** [comment]
Hi thank you for your response,
its not path issue and till now i didnt get the score from score.sh function
I wrote script that decode any audio wave and it could help anyone. I'm writing also another recipe which load the trained lm and acoustic model once.

```

 f [ ! -f path.sh ] || [ ! -f cmd.sh ]; then
    echo "Please change current directory to recipe directory e.g., examples/asr_librispeech/path.sh”
    exit 1
fi

. ./path.sh

export PYTHONPATH=$PYTHONPATH:/espresso/
# feature configuration
do_delta=false
affix=
lm_affix=
lmdir=exp/lm_lstm${lm_affix:+_${lm_affix}}
echo {$lmdir}
free_gpu=3
dir=exp/lstm${affix:+_$affix}
checkpoint=checkpoint_best.pt
lm_checkpoint=checkpoint_best.pt
kaldi_scoring=true
# decoding parameter
decode_config=
decode_dir=decode
stage=0
stop_stage=100
# download related
cmvn=/espresso/examples/asr_librispeech/data/train_960/cmvn.ark
. utils/parse_options.sh || exit 1;

train_cmd=
decode_cmd=

wav=$1
download_dir=${decode_dir}/download

if [ $# -lt 1 ]; then
    echo "${help_message}"
    exit 1;
fi

set -e
set -u
set -o pipefail


dir=${download_dir}/${models}
mkdir -p ${dir}

# Check file existence
base=$(basename $wav .wav)
decode_dir=${decode_dir}/${base}

if [ ${stage} -le 0 ] && [ ${stop_stage} -ge 0 ]; then
    echo "stage 0: Data preparation"

    mkdir -p ${decode_dir}/data
    echo "$base $wav" > ${decode_dir}/data/wav.scp
    echo "X $base" > ${decode_dir}/data/spk2utt
    echo "$base X" > ${decode_dir}/data/utt2spk
    echo "$base X" > ${decode_dir}/data/text
fi

if [ ${stage} -le 1 ] && [ ${stop_stage} -ge 1 ]; then
    echo "stage 1: Feature Generation"

   steps/make_fbank_pitch.sh --cmd "$train_cmd" --nj 1 --write_utt2num_frames true \
        ${decode_dir}/data ${decode_dir}/log ${decode_dir}/fbank

    feat_recog_dir=${decode_dir}/dump; mkdir -p ${feat_recog_dir}
    dump.sh --cmd "$train_cmd" --nj 1 --do_delta ${do_delta} \
        ${decode_dir}/data/feats.scp ${cmvn} ${decode_dir}/log \
        ${feat_recog_dir}
fi
dict=/espresso/examples/asr_librispeech/data/lang/train_960_unigram5000_units.txt
if [ ${stage} -le 1 ]; then
  echo "Stage 1: Decoding"
  opts=""
  path=$dir/$checkpoint
  decode_affix=
  lm_shallow_fusion=true
  if $lm_shallow_fusion; then
    path="$path:$lmdir/$lm_checkpoint"
    opts="$opts --lm-weight 0.47 --eos-factor 1.5"
    decode_affix=shallow_fusion
  fi
    path=/espresso/examples/asr_librispeech/exp/lstm/${checkpoint}:/espresso/examples/asr_librispeech/exp/lm_lstm/${lm_checkpoint}
    feat=${feat_recog_dir}
    text=${decode_dir}/token_text
    CUDA_VISIBLE_DEVICES=$(echo $free_gpu | sed 's/,/ /g' | awk '{print $1}') speech_recognize.py \
      --task speech_recognition --user-dir /espresso --max-tokens 15000 --max-sentences 24 \
      --num-shards 1 --shard-id 0 --test-feat-files $feat/feats.scp --test-text-files $text \
      --dict $dict --remove-bpe sentencepiece \
      --max-source-positions 9999 --max-target-positions 999 \
      --path $path --beam 60 --max-len-a 0.08 --max-len-b 0 --lenpen 1.0 \
      --results-path $dir/decode_eval${decode_affix:+_${decode_affix}} $opts \
      2>&1 | tee $dir/logs/decode_eval${decode_affix:+_${decode_affix}}.log
    if $kaldi_scoring; then
      echo "here111"
      echo "verify WER by scoring with Kaldi..."
      local/score.sh data/$dataset $dir/decode_$dataset${decode_affix:+_${decode_affix}}
      cat $dir/decode_$dataset${decode_affix:+_${decode_affix}}/scoring_kaldi/wer
    fi
fi
```

**Comment by freewym** [comment]
Cool!

**Comment by MadisKarli** [comment]
Hi

Is there a way to decode a longer audio file with multiple speakers as well? With the script above and my own attempt from SWBD recipe (only data preprocess and decode step) I only get the first utterance of the first speaker and the rest is not decoded.

With audio file longer than 100 seconds I get `Exception: Size of sample #0 is invalid (=(22760, 0)) since max_positions=(9999, 999), skip this example with --skip-invalid-size-inputs-valid-test` which makes sense since these are the parameters used when training the model.

**Comment by freewym** [comment]
I actually didn't try like that. I guess it is because the implicit LM  learned  indicates an EOS once it decoded out the first utterance. I think it may be  better to split long recordings into several utterances using something like VAD before decoding each utterances.

**Comment by MadisKarli** [comment]
Logging here as well that splitting long file into utterances based using VAD/speaker diarization helped out with longer files.
