### ISSUE TITLE
Language Model Inference

### ISSUE THREAD

**Issue by gvskalyan** [freewym/espresso#2]
How to infer a language model based on LSTM (lstm_lm) trained with subword_tokens ? (similar to generate.py for inference in seq2seq).

**Comment by gvskalyan** [comment]
sequencegenerator is used to generate sequence, say in seq2seq tasks whereas sequencescorer is used for LM to evaluate perplexity, Is there some script on the lines of interactive.py for LMs (LSTM where lstm_lm is unavailable in fairseq master) where interactive inputs could be given else is the same script csn be used with few flags?

**Comment by freewym** [comment]
So you are talking about the functionalities in the original Fariseq. I am not familiar with interactive.py. But if you want to generate sentences with subword-based LM,  [this](https://github.com/pytorch/fairseq/tree/master/examples/language_model) can give you an example of sampling a sentence from an LM.

**Comment by gvskalyan** [comment]
Got it now.. Thanks
