### ISSUE TITLE
Using wav2vec with Espresso

### ISSUE THREAD

**Issue by MadisKarli** [freewym/espresso#25]
Hi

[Wav2vec](https://github.com/freewym/espresso/tree/master/examples/wav2vec) is included under examples. Can it be used with Espresso and are there any examples where features from hdf5 files are used in Espresso?

All the best

**Comment by freewym** [comment]
Wav2vec is released by farseq. it's totally possible to use it with Espresso as they share the same codebase. You may have to read wav2vec related code to figure it out yourself though. 

There are no examples for reading from hdf5 files--you may have to do it yourself.
