### ISSUE TITLE
Deprecated `AT_CHECK` in pychain module

### ISSUE THREAD

**Issue by jinpoon** [freewym/espresso#30]
Since I don't seem to be able to report issues in PyChain, reporting the compilation issue here:
In `pychain/pytorch_binding/src/pychain.cc:23`, the `AT_CHECK` macro seems to be already deprecated in pytorch 1.5. I had to change it to `TORCH_CHECK` to finish the compilation.

**Comment by freewym** [comment]
I see there is already a PR to pychain solving this issue. I will remind the owner of PyChain repo to take care of it.

**Comment by jinpoon** [comment]
Thanks for the reply.
