### ISSUE TITLE
Request for recipe for Librispeech 100hr

### ISSUE THREAD

**Issue by PhenixCFLi** [freewym/espresso#33]
I have try to run the recipe for Librispeech 960hrs train set, it works well.
But after reduced the data to Librispeech 100hrs, I found it not working and give WER > 100% with validation set.
So would like to know if there is any recipe for Librispeech 100hrs or other train set with similar amount of data as reference ?

Thanks.

**Comment by freewym** [comment]
I don't have one for LibriSpeech 100 hrs for now. I have the WSJ recipe which is 80 hrs that you may refer to.

**Comment by PhenixCFLi** [comment]
Thanks, I have tried and it works very well.
