### ISSUE TITLE
issues about speech_fconv.py

### ISSUE THREAD

**Issue by ZhangChun96** [freewym/espresso#35]
#### What is your question?
I read your code about applying fairseq to ASR. Regarding the decoder part, I noticed that position embedding is not added to the default parameters. But since I don't have the librispeech dataset, I only used the Chinese dataset I have to do an experiment. I found that when the position embedding is not added, the loss can be reduced to about 0.6, but the decoding will appear: due to the lack of position information, the decoded sentence is too short or  will be decoded to an empty state. But when I set decoder_positional_embed to True, I found that the loss will start to oscillate around 3. I want to ask if this phenomenon occurs because I haven't trained enough epochs. (According to experience, the loss generally needs to be reduced to below 1 and the decoded result can be partially correct) 
#### Code

![image](https://user-images.githubusercontent.com/67884280/88026990-3fc37480-cb69-11ea-8fae-f2365cf1c054.png)

Besides,  I saw the fairseq paper, the implementation of fposition embedding is different from the traditional sine and cosine formula. I want to ask if I can adjust the weight when adding x and pos_emb? Thanks a lot!

**Comment by freewym** [comment]
I am not maintaining speech_fconv for a while. If you are interested in how positional embeddings is used, you can take a look at speech_transformer, where it is using sine/cosine formula.
