### ISSUE TITLE
GPU utilization is very low

### ISSUE THREAD

**Issue by yfliao** [freewym/espresso#39]
Dear All,

I'm running the asr_librispeech recipe in an ubuntu 16.04 virtual machine with 4 V100s.

My problem is that the CPUs are all busy but the GPU utilization is always very low. So the training speed is slow (both in the LSTM and transformer cases). How to solve this issue?

Thanks a lot!

<pre><code>
top - 19:31:44 up 3 days, 16:48,  1 user,  load average: 68.33, 76.75, 61.09
Tasks:  14 total,   5 running,   9 sleeping,   0 stopped,   0 zombie
%Cpu(s):  9.0 us, 25.6 sy,  0.0 ni, 65.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 52826323+total, 21278182+free, 35688764 used, 27979264+buff/cache
KiB Swap:        0 total,        0 free,        0 used. 48815801+avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                          
34316 liao      20   0 32.798g 7.950g 541428 R 791.4  1.6 128:56.46 python3                                                                                                                                                          
34315 liao      20   0 32.940g 7.943g 532860 R 701.7  1.6 166:19.57 python3                                                                                                                                                          
34317 liao      20   0 32.643g 7.951g 542212 R 636.9  1.6 141:01.29 python3                                                                                                                                                          
34318 liao      20   0 32.706g 7.952g 542148 R 613.0  1.6 139:37.17 python3                                                                                                                                                          
</pre></code>

<pre><code>
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
| N/A   42C    P0    85W / 300W |   3902MiB / 16160MiB |     17%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
| N/A   44C    P0    78W / 300W |   3890MiB / 16160MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
| N/A   49C    P0   162W / 300W |   3902MiB / 16160MiB |      6%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
| N/A   45C    P0   169W / 300W |   3900MiB / 16160MiB |     17%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
</pre></code>

**Comment by freewym** [comment]
Would it be faster when using 2 GPUs? Or does increasing batch size solve this issue? I am trying to figure out  whether the problem is because of using more than 2 GPUs, or simply because the batch size you set is not large enough.
