### ISSUE TITLE
Results.md request with ASR Recipes, SWBD Scores w/o LM

### ISSUE THREAD

**Issue by roshansh-cmu** [freewym/espresso#40]
#### What is your question?
What numbers are expected with the SWBD Transformer? 
I have built AM only models with LSTM and Transformer Models and get similar numbers

LSTM: SWBD (10.4), CALLHM(20.7)
Transformer: SWBD(10.8),CALLHM(20.8)

How much improvement does Specaug give?
I am seeing no improvement with Transformers + Specaug compared to Transformers w/o Specaug?

Could you please add a RESULTS.md file with each recipe which has current best working numbers to compare to?

Note: With LSTM based AM and LM, I was able to match your paper reported numbers

**Comment by freewym** [comment]
AM only model (both with 2 GTX 1080 Ti GPUs)
                                                 SWBD      CALLHM
LSTM (pytorch 1.1)                     10.7          20.7
Transformer (pytorch 1.4)         10.5          20.2

I haven't test Specaug with transformers. I just copy over the same specaug config as for LSTM. You may have to tune the specaug related options specific to transformers.

OK, I will add the result file later.

**Comment by roshansh-cmu** [comment]
Thanks for your reply. I will share configs if I can improve on your numbers.
