### ISSUE TITLE
Support for RNNLM use while decoding?

### ISSUE THREAD

**Issue by prashantserai** [freewym/espresso#42]
Does Espresso support Beam search decoding with RNNLM or another LM?

Also is there a version requirement for KALDI? Which KALDI installation is ok to connect to Espresso?

**Comment by freewym** [comment]
Yes. Please see an example of the decoding script in run.sh of any one of the recipes (WSJ, Librispeech or SWBD).

I think any version of Kaldi within the recent years is fine.
