### ISSUE TITLE
AttributeError: 'SpeechRecognitionEspressoTask' object has no attribute 'feat_dim'

### ISSUE THREAD

**Issue by krishnanpooja** [freewym/espresso#43]
## 🐛 Bug

The SpeechRecognitionEspressoTask has no attribute 'feat_dim'. Issue seen when trying to evaluate the model.

### To Reproduce

Steps to reproduce the behavior (always include the command you ran):

Try to import pretrained model using checkpoint file.
See error
```
model = models.build_model(args, self)
File "git/espresso/fairseq/models/init.py", line 48, in build_model
return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
File "git/espresso/espresso/models/speech_transformer.py", line 128, in build_model
logger.info("input feature dimension: {}, channels: {}".format(task.feat_dim, task.feat_in_channels))
AttributeError: 'SpeechRecognitionEspressoTask' object has no attribute 'feat_dim'
```

### Expected behavior

No error

### Environment

fairseq Version (e.g., 1.0 or master): 0.9.0
PyTorch Version (e.g., 1.0) 1.6.0
OS (e.g., Linux): Linux
How you installed fairseq (pip, source): pip

**Comment by freewym** [comment]
Did you call `task.load_dataset()` before `checkpoint_utils.load_model_ensemble()`? `feat_dim` is created in `task.load_dataset()`?

**Comment by krishnanpooja** [comment]
I am trying to load a pretrained checkpoint file and get prediction for a particular sample. Are we expected to call task.load_dataset() separately?

**Comment by freewym** [comment]
feat_dim is defined in task.load_dataset(), and I didn't expect that you would directly feed a sample instead of loading a dataset. Or you can just do some hack in the task's constructor to create feat_dim there (e.g. `self.feat_dim = 83`).

**Comment by krishnanpooja** [comment]
I am already doing that hack:-) I'll try calling the task.load_dataset() explicitly.

**Comment by freewym** [comment]
Now feat_dim is obtained within `build_task()` and is then passed to the task constructor.
