### ISSUE TITLE
Instructions for Training from Scratch?

### ISSUE THREAD

**Issue by kalpitdixit** [freewym/espresso#5]
Hi,
Thanks for releasing this code.
I am trying to do ASR for Gujarati (an Indian Language) and have custom labelled data. It would be great it you could release a README file for:
1. how to train models from scratch
2. how to perform inference from scratch

Thanks,
Kalpit

**Comment by freewym** [comment]
You can take [WSJ recipe](https://github.com/freewym/espresso/blob/master/examples/asr_wsj/run.sh) for reference. Like in stage 0&1, you need to use Kaldi for preparing feature/text files (you can use some of the scripts provided in Espresso for doing that). Stage 2 is creating dictionary and tokenizing text into sequences of characters depending on your language (AFAIK Gujarati can follow the same procedure). The following stages are training LM and E2E models and then decoding.

**Comment by freewym** [comment]
I'm going to close it. If you have further questions you can still raise them here.
