### ISSUE TITLE
Different WERs when decoding with different batch size (--max-sentences)

### ISSUE THREAD

**Issue by joyolee** [freewym/espresso#52]
Hi,
I would ask the reason why I get different results when I decode with different batch sizes. (--max-sentences).

For example, with the same language model and same attention-based encoder-decoder model:

1. by setting the batch size (--max-sentences) as 32, in WSJ, the WER is 3.46% in eval92 and 5.71% in dev93.
2. by setting the batch size (--max-sentences) as 1, in WSJ, the WER is 3.42% in eval92 and 5.67% in dev93.

The difference is not large, I guess this issue is caused by the beam search in batches. But I'm not sure clearly where the difference comes from. If you know, I'm glad to have your answer.

**Comment by freewym** [comment]
Yes, I also observed such things before. Yes I also think it's caused by the beam search code `sequence_generator.py`. I haven't investigate into this as the code is almost from fairseq, Not sure if people doing MT with fairseq have encountered the same problem.

**Comment by joyolee** [comment]
> Yes, I also observed such things before. Yes I also think it's caused by the beam search code `sequence_generator.py`. I haven't investigate into this as the code is almost from fairseq, Not sure if people doing MT with fairseq have encountered the same problem.

Thanks for your prompt reply. I might have a check if the people in MT also have similar things later, or submit an issue in fairseq.

**Comment by freewym** [comment]
The thread in #55 may suggest the reason: the encoder's convolution may give different output  when input features are padded differently in different batches

**Comment by joyolee** [comment]
I would ask if this problem is fixed? I submitted an issue in fairseq, and the author suspects that this problem could be caused by the missing padding mask after each layer. [https://github.com/pytorch/fairseq/issues/3078#issuecomment-754858923](url)

**Comment by freewym** [comment]
After looking at the issue I mentioned in my last post, I agree that the encoder's padding is the cause. But I think it only happens with convolutions (not confirmed yet): the shorter examples in a batch will be padded with different padding frames in different batches, making the convolution kernel being applied across the example boundary get different numbers.
