### ISSUE TITLE
Build PyChain with CPU

### ISSUE THREAD

**Issue by Shanboy5566** [freewym/espresso#54]
Hi 
Is there any method to compile and use pychain on CPU?

**Comment by Shanboy5566** [comment]
https://github.com/YiwenShaoStephen/pychain/pull/11
I tried this but it can't work.

ImportError: /root/sh_env/lib/python3.6/site-packages/pychain_C-0.0.0-py3.6-linux-x86_64.egg/pychain_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN25ChainLogDomainComputationC1EN2at6TensorES1_S1_S1_S1_S1_S1_S1_S1_S1_S1_S1_i

**Comment by freewym** [comment]
Did PyChain compile without errors? Would uninstall and re-install PyTorch and PyChain help? I see a similar solution in
https://github.com/facebookresearch/maskrcnn-benchmark/issues/891

**Comment by Shanboy5566** [comment]
I re-install PyTorch and re-compile PyChain but it still has same error.

**Comment by freewym** [comment]
Does it only happen when compiled with CPU?

**Comment by Shanboy5566** [comment]
Yes.

**Comment by freewym** [comment]
Sorry I have no clues... I know people can compile PyChain with GPUs and then use it with CPUs. Not sure if you could ask the author of that PR for more info
