### ISSUE TITLE
SpecAug slows down training time

### ISSUE THREAD

**Issue by timolohrenz** [freewym/espresso#56]
Hey there,

   I am training a Librispeech transformer on 4 P100 GPUs which works fine so far with ~1.1h/epoch. As I was now experimenting with specAug, I noticed that the training time doubles with ~2.38h/epoch.

Is this expected behaviour? 

I suspected that SpecAug might be part of dataloading so I tried to increase num-workers during training to something > 0, but that gave me errors which seems to be caused by an insufficient shared memory size (which I unfortunately cannot change due to missing root privileges).

So is there any other way to speed up SpecAug training?  

Thanks, Timo

**Comment by freewym** [comment]
SpecAug  is applied to the loaded feature matrices on-the-fly at https://github.com/freewym/espresso/blob/master/espresso/data/feat_text_dataset.py#L185.

You can turn off time warping at https://github.com/freewym/espresso/blob/master/espresso/tools/specaug_interpolate.py#L45
for speed-up

**Comment by timolohrenz** [comment]
Thanks for that info. That will help. 

I will try to turn off TimeWarp and report epoch time improvment (and probably WERs) here, as it might help others.

**Comment by timolohrenz** [comment]
To conclude this, these are results I achive on Librispeech with different SpecAug settings. Speed up by turning off TimeWarp was quite significant while results are quite on par (better in clean, worse in other)

![image](https://user-images.githubusercontent.com/25075084/110920001-28661100-831d-11eb-87e3-bb9113b1bf68.png)

Please note that these results are not comparable to the current librispeech recipes, as we tweaked some parameters and used a slightly bigger LM. 

Are there any simple steps in tuning the librispeech recipe? The only differences that I can make out compared to ESPnet is the multi-task CTC/attention loss, model averaging over the last epochs, and slightly different CNN frontends. I am wondering if these are really responsible for the remaining gap in performance.

**Comment by freewym** [comment]
I remember I got better WER 2.3/5.9 on test-clean/other with LSTM E2E model + LSTM LM fusion. You said your LM is bigger, so I assume it would be better (?).

What is the numbers in ESPnet? Are they based on Transformers or LSTMs?
