### ISSUE TITLE
WSJ Recipe: "wsj_data_prep.sh: Spot check of command line arguments failed"

### ISSUE THREAD

**Issue by mrazizi** [freewym/espresso#57]
#### What is your question?

I am trying to run wsj recipe using ``./run.sh`` but I get the following error:

```
Stage 0: Data Preparation
ln: failed to create symbolic link 'links/??-?.?': File exists
ln: failed to create symbolic link 'links/??-??.?': File exists
wsj_data_prep.sh: Spot check of command line arguments failed
Command line arguments must be absolute pathnames to WSJ directories
with names like 11-13.1.
Note: if you have old-style WSJ distribution,
local/cstr_wsj_data_prep.sh may work instead, see run.sh for example.
``` 

#### Code

```
./run.sh
```

#### What have you tried?

I don't see ``cstr_wsj_data_prep.sh`` in local directory of wsj directory.

```
!ls local/cstr_wsj_data_prep.sh
```

```
ls: cannot access 'local/cstr_wsj_data_prep.sh': No such file or directory
```

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 1.0
 - PyTorch Version (e.g., 1.0): 1.7.0+cu101
 - OS (e.g., Linux): Google Colab (Linux)
 - How you installed fairseq (`pip`, source): ``pip install --editable .`` in espresso source code
 - Build command you used (if compiling from source): *To install Espresso* commands in readme
 - Python version: 3.6
 - CUDA/cuDNN version: Not using GPU now
 - GPU models and configuration: Not using GPU now, my problem is in downloading dataset stage
 - Any other relevant information: I am using source code from master branch

**Comment by freewym** [comment]
see if  `data/local/data/links` exists. if yes. remove it before re-run the script.
