### ISSUE TITLE
SpecAugment is not used due to a typo in the prefetch_called assignment

### ISSUE THREAD

**Issue by slikos** [freewym/espresso#59]
In line 147 of feat_text_dataset.py must be 
self.prefetch_called = True
not
self.prefetched_called = True

https://github.com/freewym/espresso/blob/f59f3956b07dba0f131828a4aa5566fcb856e9ba/espresso/data/feat_text_dataset.py#L147

**Comment by freewym** [comment]
Thanks! Fixed.
