### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by kalpitdixit** [freewym/espresso#6]
In one of the READMEs, https://github.com/freewym/espresso/tree/master/examples/speech_recognition#training-librispeech-data,

the command used is `python train.py ...` but that folder does not have a `train.py` file.

**Comment by freewym** [comment]
Code/scripts from that folder are from original fairseq. Espresso's LibriSpeech recipe is in `examples/asr_librispeech`.

Anyways, I think the `train.py` file it is referring to is in the root directory.

**Comment by kalpitdixit** [comment]
👍
