### ISSUE TITLE
Error in training stage of run_chain_e2e_bichar.sh:  'odict_items' object is not an iterator

### ISSUE THREAD

**Issue by mohsen-goodarzi** [freewym/espresso#67]
I am trying to train a mode on a custom dataset.
All the data preparation stages are done flawlessly (at least seems like that).
But at the begining of the training stage (stage =6) of run_chain_e2e_bichar.sh I get the following error:

`<class 'odict_items'>
Traceback (most recent call last):
  File "../../fairseq_cli/train.py", line 510, in <module>
    cli_main()
  File "../../fairseq_cli/train.py", line 503, in cli_main
    distributed_utils.call_main(cfg, main)
  File "../../fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "../../fairseq_cli/train.py", line 86, in main
    task = tasks.setup_task(cfg.task)
  File "../../espresso/fairseq/tasks/__init__.py", line 44, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "../../espresso/espresso/tasks/speech_recognition_hybrid.py", line 432, in setup_task
    src_dataset = get_asr_dataset_from_json(data_path, split, dictionary, combine=False).src
  File "../../espresso/espresso/tasks/speech_recognition_hybrid.py", line 236, in get_asr_dataset_from_json
    if "feat" in next(loaded_json.items()):
TypeError: 'odict_items' object is not an iterator`

I also tried the biphone trainaing (run_chain_e2e.sh) and got exactly the same error.
Any Ideas on what is the problem or what I am doing wrong are appreciated.
Thank you.

 - espresso Version: master
 - PyTorch Version: 1.8.1
 - OS: CentOS Linux 7
 - Python version: 3.6

**Comment by freewym** [comment]
`next(loaded_json.items())` -> `next(iter(loaded_json.items()))`

Probably it will fix the issue (pushed)

**Comment by mohsen-goodarzi** [comment]
Thank you! It solved that issue, ...
... but now I stuck with following issue (Although I don't think it is related to above one!):
`Traceback (most recent call last):
  File "../../fairseq_cli/train.py", line 510, in <module>
    cli_main()
  File "../../fairseq_cli/train.py", line 503, in cli_main
    distributed_utils.call_main(cfg, main)
  File "espresso/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "../../fairseq_cli/train.py", line 86, in main
    task = tasks.setup_task(cfg.task)
  File "espresso/fairseq/tasks/__init__.py", line 44, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "espresso/espresso/tasks/speech_recognition_hybrid.py", line 423, in setup_task
    src_dataset = get_asr_dataset_from_json(data_path, split, dictionary, combine=False).src
  File "espresso/espresso/tasks/speech_recognition_hybrid.py", line 249, in get_asr_dataset_from_json
    tgt_datasets.append(NumeratorGraphDataset(utt_ids, numerator_fsts))
  File "espresso/espresso/data/asr_chain_dataset.py", line 97, in __init__
    self.read_fsts(utt_ids, rxfiles)
  File "espresso/espresso/data/asr_chain_dataset.py", line 113, in read_fsts
    fst = simplefst.StdVectorFst.read_ark(file_path, offset)
TypeError: read_ark(): incompatible function arguments. The following argument types are supported:
    1. (arg0: str, arg1: int) -> simplefst.StdVectorFst

Invoked with: 'espresso/examples/asr_hsa/exp/chain/e2e_bichar_tree/fst_nor.1.ark', 12998914734`

Please consider that my fst_nor.#.ark files are pretty big even though my dataset is relatively small!
Shouldn't the nominator fst file be smaller than den.fst?
Is there some problem with my fst_nor files?

**Comment by mohsen-goodarzi** [comment]
> UPDATED:
> 
> > `next(loaded_json.items())` -> `next(iter(loaded_json.items()))`
> > Hopefully it will fix the issue (pushed)
> 
> Thank you! It solved that issue, ...
> ... but now I stuck with following issue (Although I don't think it is related to above one!):
> 
> `Traceback (most recent call last): File "../../fairseq_cli/train.py", line 510, in <module> cli_main() File "../../fairseq_cli/train.py", line 503, in cli_main distributed_utils.call_main(cfg, main) File "/mnt/IDMT-WORKSPACE/DATA-STORE/gzi/train-lvcsr/espresso/fairseq/distributed/utils.py", line 369, in call_main main(cfg, **kwargs) File "../../fairseq_cli/train.py", line 86, in main task = tasks.setup_task(cfg.task) File "/mnt/IDMT-WORKSPACE/DATA-STORE/gzi/train-lvcsr/espresso/fairseq/tasks/__init__.py", line 44, in setup_task return task.setup_task(cfg, **kwargs) File "/mnt/IDMT-WORKSPACE/DATA-STORE/gzi/train-lvcsr/espresso/espresso/tasks/speech_recognition_hybrid.py", line 423, in setup_task src_dataset = get_asr_dataset_from_json(data_path, split, dictionary, combine=False).src File "/mnt/IDMT-WORKSPACE/DATA-STORE/gzi/train-lvcsr/espresso/espresso/tasks/speech_recognition_hybrid.py", line 262, in get_asr_dataset_from_json text_datasets.append(AsrTextDataset(utt_ids, text, dictionary, append_eos=False)) File "/mnt/IDMT-WORKSPACE/DATA-STORE/gzi/train-lvcsr/espresso/espresso/data/feat_text_dataset.py", line 287, in __init__ self.read_text(utt_ids, texts, dictionary) File "/mnt/IDMT-WORKSPACE/DATA-STORE/gzi/train-lvcsr/espresso/espresso/data/feat_text_dataset.py", line 302, in read_text self.sizes = [len(tokenize_line(text)) for text in texts] File "/mnt/IDMT-WORKSPACE/DATA-STORE/gzi/train-lvcsr/espresso/espresso/data/feat_text_dataset.py", line 302, in <listcomp> self.sizes = [len(tokenize_line(text)) for text in texts] NameError: free variable 'tokenize_line' referenced before assignment in enclosing scope`


I solved it by taking the following import line out of if statement (line 296 of espresso/espresso/data/feat_text_dataset.py):

```
        from fairseq.tokenizer import tokenize_line
        if dictionary is not None:
            

            self.sizes = [
                len(tokenize_line(dictionary.wordpiece_encode(text))) + (1 if self.append_eos else 0)
                for text in texts
            ]
        else:
            self.sizes = [len(tokenize_line(text)) for text in texts]
```

**Comment by freewym** [comment]
great. pushed the fix as well.
