### ISSUE TITLE
Transformer LM in ASR

### ISSUE THREAD

**Issue by marthayifiru** [freewym/espresso#69]
Hi,
Thanks you for providing the transformer ASR recipe. Is it possible to use transformer language model instead of lstm? I have seen the recipe run script, it provides use_transformer option in the Acoustic Model training. But in the language model training it does not provide such option.

Thank you in advance for your answer.
Martha.

### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by freewym** [comment]
There is a transformer lm defined in https://github.com/freewym/espresso/blob/master/fairseq/models/transformer_lm.py. You can leverage that.

**Comment by marthayifiru** [comment]
Thanks a lot, I will try to use it.
