### ISSUE TITLE
'frame_subsampling_factor' in chain e2e setup

### ISSUE THREAD

**Issue by mohsen-goodarzi** [freewym/espresso#70]
In the Kaldi setup for chain (i.e. LF-MMI), there is a parameter called frame_subsampling_factor which is always set to 3. This is used to reduce the computational burden of LF-MMI loss.  
Unfortunately I was not able to spot this parameter in your chain-e2e setup [(run_chain_e2e_bichar.sh)](https://github.com/freewym/espresso/blob/master/examples/asr_wsj/run_chain_e2e_bichar.sh).

Is it hard coded some where or it is implemented in a different way?
I would be grateful if you can guide me on this.

**Comment by freewym** [comment]
frame subsampling can be achieved within the network itself: e.g. you can simply set the stride of the last convolutional layer to 3 to get 3x subsampling (at https://github.com/freewym/espresso/blob/master/examples/asr_wsj/run_chain_e2e_bichar.sh#L201).

**Comment by mohsen-goodarzi** [comment]
Oh! Now I see it!  
Thank you!
